swagger: "2.0"
info:
  description: Academic Registration system swagger file for server code
  version: "1.0.0"
  title: Academic Registration System REST
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by server application
paths:
  /professors:
    get:
      operationId: "professors.read_all"
      tags:
        - "Professors"
      summary: "The professors data structure supported by the server application"
      description: "Read list of professors"
      responses:
        200:
          description: "Successful read professors list operation"
          schema:
            type: "array"
            items:
              properties:
                p_id:
                  type: "string"
                fname:
                  type: "string"
                lname:
                  type: "string"
    post:
      operationId: "professors.create"
      tags:
        - "Professors"
      summary: "Create a professor and add it to the professors list"
      description: "Create a new professor on the professors list"
      parameters:
        - name: "professor"
          in: "body"
          description: "Professor to create"
          required: True
          schema:
            type: "object"
            properties:
              p_id:
                type: "string"
                description: "P_ID of professor to create"
              fname:
                type: "string"
                description: "Name of professor to create"
              lname:
                type: "string"
                description: "Name of professor to create"
      responses:
        201:
          description: "Successfully created professor in list"

