swagger: "2.0"
info:
  description: Academic Registration system swagger file for server code
  version: "1.0.2"
  title: Academic Registration System API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by server application
paths:
  /professors:
    get:
      operationId: "professors.read_all"
      tags:
        - "Professors"
      summary: "GET all Professors"
      description: "GET all professors from database"
      responses:
        200:
          description: "Successful GET Professors"
          schema:
            type: "array"
            items:
              properties:
                p_id:
                  type: "integer"
                  description: "ID of Professor"
                fname:
                  type: "string"
                  description: "First name of Professor"
                lname:
                  type: "string"
                  description: "Last name of Professor"
    post:
      # operationId -> Identify which python function should handle url
      operationId: "professors.create"
      tags:
        - "Professors"
      summary: "Create a new Professor"
      description: "Create a new Professor with POST request"
      parameters:
        - name: "professor"
          in: "body"
          description: "Professor to create"
          required: True
          schema:
            type: "object"
            properties:
              fname:
                type: "string"
                description: "First name of professor to create"
              lname:
                type: "string"
                description: "Last name of professor to create"
      responses:
        201:
          description: "Successfully created Professor in db"
          schema:
            properties:
              p_id:
                type: "integer"
                description: "ID of Professor"
              fname:
                type: "string"
                description: "First name of Professor"
              lname:
                type: "string"
                description: "Last name of Professor"

  /courses:
    get:
      operationId: "courses.read_all"
      tags:
        - "Courses"
      summary: "GET all Courses"
      description: "GET Courses from database"
      responses:
        200:
          description: "Successful GET courses"
          schema:
            type: "array"
            items:
              properties:
                c_id:
                  type: "integer"
                  description: "ID of Course"
                title:
                  type: "string"
                  description: "Title of Course"
                p_id:
                  type: "string"
                  description: "ID of Professor(s) assigned to Course"
    post:
      operationId: "courses.create"
      tags:
        - "Courses"
      summary: "Create a new Course"
      description: "Create a new Course with POST request"
      parameters:
        - name: "course"
          in: "body"
          description: "Course to create"
          required: True
          schema:
            type: "object"
            properties:
              title:
                type: "string"
                description: "Title of Course to create"
              p_id:
                type: "integer"
                description: "P_ID of Professor to assign to Course"
      responses:
        201:
          description: "Successfully created Course"
          schema:
            properties:
              c_id:
                type: "integer"
                description: "ID of Course"
              title:
                type: "string"
                description: "Title of Course"
              p_id:
                type: "string"
                description: "ID of Professor(s) assigned to Course"

  /students:
    get:
      operationId: "students.read_all"
      tags:
        - "Students"
      summary: "GET all Students"
      description: "GET Students from database"
      responses:
        200:
          description: "Successful GET Students"
          schema:
            type: "array"
            items:
              properties:
                s_id:
                  type: "integer"
                  description: "ID of Student"
                fname:
                  type: "string"
                  description: "First name of Student"
                lname:
                  type: "string"
                  description: "Last name of Student"
    post:
      operationId: "students.create"
      tags:
        - "Students"
      summary: "Create a new Student"
      description: "Create a new Student with POST request"
      parameters:
        - name: "student"
          in: "body"
          description: "Student to create"
          required: True
          schema:
            type: "object"
            properties:
              fname:
                type: "string"
                description: "Name of Student to create"
              lname:
                type: "string"
                description: "Name of Student to create"
      responses:
        201:
          description: "Successfully created new Student"
          schema:
            properties:
              s_id:
                type: "integer"
                description: "ID of Student"
              fname:
                type: "string"
                description: "First name of Student"
              lname:
                type: "string"
                description: "Last name of Student"

  /registries:
    get:
      operationId: "registries.read_all"
      tags:
        - "Registries"
      summary: "GET all Registries"
      description: "GET all Registries from database"
      responses:
        200:
          description: "Successful GET Registries"
          schema:
            type: "array"
            items:
              properties:
                r_id:
                  type: "integer"
                  description: "ID of Registry"
                c_id:
                  type: "integer"
                  description: "ID of Course registered for by Student"
                s_id:
                  type: "integer"
                  description: "ID of Student registered for Course"
    post:
      operationId: "registries.create"
      tags:
        - "Registries"
      summary: "Create a new Registry"
      description: "Create a new Registry with POST request"
      parameters:
        - name: "registry"
          in: "body"
          description: "Registry to create"
          required: True
          schema:
            type: "object"
            properties:
              c_id:
                type: "integer"
                description: "ID of course to register"
              s_id:
                type: "integer"
                description: "ID of student to register"
      responses:
        201:
          description: "Successfully created student in list"
          schema:
            properties:
              r_id:
                type: "integer"
                description: "ID of Registry"
              c_id:
                type: "integer"
                description: "ID of Course registered for by Student"
              s_id:
                type: "integer"
                description: "ID of Student registered for Course"